### ISSUE TITLE
Renommage de l'endpoint d'accès aux fiches d'identités 

### ISSUE THREAD

**Issue by brindu** [etalab/rncs_worker_api_entreprise#100]
Je propose un renaming de `/infos_identite_entreprise` aujourd'hui en `/fiches_identite`.

Je trouve l'existant un peu long, et comme on release bientôt ce sera l'occasion ici de valider ici le nom de l'endpoint choisi.

C'est pas seulement parce que je trouve l'actuel trop long : 
* pas fan du "infos", on fait du REST et on sait qu'un `get` sur la ressource renvoie les infos de cette ressource.
* pas convaincu à 100% pour `identites_entreprise`, on a déjà eu la discussion avec @giglemad  sur le mot clé "entreprise" car on n'a pas que des entreprises dans le RNCS.

Du coup je propose `fiches_identite` : c'est francisé, c'est clair et le mot "fiche" sera aussi présent partout sur le site et dans les docs (à cause du mot interdit), et pas besoin du "infos" (c'est REST compliant).

WDYT @giglemad @Haelle ?

**Comment by Haelle** [comment]
Très bonne idée, j'avais aussi en tête de les renommer pour les mêmes raisons.
J'ai pas de proposition de nom et j'aime bien `fiche_identite`

**Comment by brindu** [comment]
Pour du REST le nom de la ressource dans l'URL est bien au pluriel. 
Et oui uniquement `show` comme action, mais ça n'impact pas l'orthographe de la ressource.

**Comment by giglemad** [comment]
Ok pour moi
