### ISSUE TITLE
Ajouter un message d'erreur quand l'entreprise n'est pas au RNCS

### ISSUE THREAD

**Issue by Haelle** [etalab/rncs_worker_api_entreprise#145]
Aujourd'hui le message d'erreur quand on ne trouve pas l'inscription principale et le même que lorsqu'il n'y a aucune inscription du tout.
Cela ne permet pas d'avoir la différence entre :
- une entreprise dont la fiche n'est pas faisable
- une entreprise non inscrite au RNCS / inexistante

**Comment by brindu** [comment]
Bon et bien je crois qu'il est temps de faire ce [TODO](https://github.com/etalab/rncs_worker_api_entreprise/blob/master/app/models/dossier_entreprise.rb#L17) 😂
