### ISSUE TITLE
Premier stock de donnée introuvable

### ISSUE THREAD

**Issue by wibimaster** [etalab/rncs_worker_api_entreprise#169]
Bonjour, 

La commande donnée dans la documentation : 
`TribunalCommerce::Stock::Operation::Import.call(stock_args: my_stock)`

Me retourne une erreur, car il va chercher les fichiers en local :

> Starting import : looking for stock 2017/05/04 in file system...
> Specified stock ./local_data/opendata-rncs.inpi.fr/public/IMR_Donnees_Saisies/tc/stock/2017/05/04 is not found. Ensure the stock to import exists. Aborting...

Comment obtenir ces données la première fois, y a t'il une URL pour les télécharger soi-même ?

Merci !

**Comment by brindu** [comment]
Bonjour, 

Les données ne sont pas disponibles dans le répertoires des sources, il faut en demander l'accès à l'INPI et ensuite paramétrer le dossier où se trouvent les données brutes (les fichiers téléchargés depuis le FTP de l'INPI). 

Vous trouverez normalement sur [cette page](https://www.inpi.fr/fr/immatriculations-modifications-radiations-des-societes-imr) un formulaire de demande d'accès auprès de l'INPI.

Bonne journée !
