### ISSUE TITLE
Daily update depuis le 04 mai 2017

### ISSUE THREAD

**Issue by mpo-deltacode** [etalab/rncs_worker_api_entreprise#172]
Bonjour, j'aurai une question par rapport aux mises a jour depuis l'import de base de 2017

J'ai donc ma base de données qui date de l'import du 4 mai 2017 et j'aimerai qu'elle se mette a jour jusqu'a la date d'aujourd'hui (janvier 2021)

J'essai donc de lancer la commande `TribunalCommerce::DailyUpdate::Operation::Load.call` avec en ftp-path `opendata-rncs.inpi.fr/public/IMR_Donnees_Saisies`. Mais la console Rails me retourne une erreur comme quoi il n'y aurait pas de daily update depuis le 2017-05-04

Je pense donc qu'il faut que mon script se connecte au FTP afin de récuperer les données mais je ne comprend pas comment faire pour m'y connecter a partir des scripts.

Je souhaiterai donc que vous m'expliquiez comment récuperer les données de mai 2017 a aujourd'hui a partir des script de daily update.

Merci d'avance

PS : j'arrive a récuperer des fichiers de décembre 2020 mais en utilisant directement la commande `wget` dans mon ubuntu avec mes identifiants du FTP

**Comment by brindu** [comment]
Bonjour, 

Les scripts d'imports ne se connectent pas au FTP, les flux quotidiens doivent être synchronisés en local auparavant (comme vous l'avez fait pour le stock du 4 mai 2017, car si je comprends bien celui-ci a été importé et votre base est à jour du stock). 

Il y un job qui synchronise quotidiennement les nouveaux flux présent sur le FTP de l'INPI : https://github.com/etalab/rncs_worker_api_entreprise/blob/master/app/jobs/sync_ftp_job.rb 

Comme indiqué dans le [README](https://github.com/etalab/rncs_worker_api_entreprise#configuration-files) vous devez configurer le dossier dans lequel vous souhaitez stocker les flux télécharger depuis le FTP. Ceci même si vous faites un import manuel sans utiliser le job car les scripts d'imports en base utilisent ce fichier de configuration pour identifier le path où se trouvent les flux quotidiens à importer.

Pour une syncro automatique avec le FTP il faut renseigner vos identifiants de connexions dans les fichiers de configuration (cela manque de la README actuellement), mais vous pouvez voir [ici](https://github.com/etalab/rncs_worker_api_entreprise/blob/master/app/jobs/sync_ftp_job.rb#L44) comment ils doivent être renseignés. 

En espérant avoir répondu à vos questions.

**Comment by mpo-deltacode** [comment]
Bonjour,

Oui vous avez répondu a mes questions, merci beaucoup. Je voudrais juste maintenant savoir comment lancer le job qui permet de synchroniser quotidiennement les nouveaux flux dans le FTP ? Par une commande dans la console Rails ? Ou bien il y a une commande Rake pour lancer le job sur Sidekiq ?

Merci d'avance

**Comment by brindu** [comment]
Bonjour, 

Les jobs sont programmés dans le fichier [config/schedule.yml](https://github.com/etalab/rncs_worker_api_entreprise/blob/master/config/schedule.yml) et exécutés automatiquement par [Sidekiq-Cron](https://github.com/ondrejbartas/sidekiq-cron). 

Il vous suffit normalement de configurer un service Sidekiq, vous pouvez trouver un exemple de configuration systemd [ici](https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service). 

Quand tout est en ordre il est possible d'accéder au job programmés par Sidekiq-Cron directement de la web UI de Sidekiq.

**Comment by mpo-deltacode** [comment]
Bonjour,

Merci pour votre reponse, j'ai pu relancer mon service Sidekiq en lui ajoutant l'option `-C` et le fichier schedule.yml

J'aurais une derniere question. Je pense deja connaitre la réponse mais je préfère etre sur. Comme je l'ai dis plus haut, pour faire les mises a jours de mai 2017 à aujourd'hui, je les fais manuellement en téléchargeant les fichiers par une commande wget, puis un script qui va lancer les deux scripts de vérification de la conformité des données  (`check_rfc4180_compliant.bash` et `clean_csv.bash`) et au final j'accède a la console Rails pour charger ses mises a jour dans la base et les importer (j'ai modifié certains fichiers Ruby, ca peut etre la cause de mon problème je pense). Tout a l'air de fonctionner, mais une fois les imports fini, le nombre de ligne n'a pas l'air d'avoir bougé. Exemple dans la table personne physique, de mai 2017 a novembre 2017, je n'ai pas de ligne en plus ou en moins, alors que le champs `date de derniere modification` lui à bien changé. Est ce normal qu'il y ai toujours le même nombre de ligne dans les tables après les imports, ou est ce que c'est un problème ? (au quel cas, il doit surement venir de mes modifications des fichiers Ruby)

Merci encore une fois d'avance

**Comment by mpo-deltacode** [comment]
Bonjour, merci pour votre aide, j'ai résolu mes différents problèmes
