### ISSUE TITLE
Syncro lftp trop longue

### ISSUE THREAD

**Issue by Haelle** [etalab/rncs_worker_api_entreprise#88]
Aujourd'hui la commande de sync avec lftp prend 3h c'est trop long.
Trouver une solution alternative

**Comment by brindu** [comment]
Yep c'est un peu sauvage de tout synchroniser à chaque fois je te l'accorde. J'ai essayé de récupérer uniquement le mois en cours et le mois précédent avec les options *--include-dir* et *--exclude-dir* de lftp sans succès... Il va falloir faire un petit script plus intelligent avec des *chdir* un peu dans tous les sens.

Rien de bien méchant faudra juste prend un peu de temps pour le faire. En attendant, trois heures c'est pas bloquant, je vais lancer l'import en base tous les jours à 10h pour prendre large, de toute façon il y a déjà un jour de délai.

**Comment by brindu** [comment]
Fix in #126
