### ISSUE TITLE
Refactor DB Current Date

### ISSUE THREAD

**Issue by Haelle** [etalab/rncs_worker_api_entreprise#89]
Il faut revoir le fonctionnement des deux opérations DBCurrentDate (TC et TITMC).
Aujourd'hui cette date qui sert à plusieurs chose, on l'affiche dans le front et les PDF, ça sert à importer les mises à jours, la notion doit être affinée

Il pourrait être intéressant d'en faire un modèle avec quelques méthodes:

- `last_update(type)`
- `last_stock_update(type)`
- `last_daily_update(type)`

type: tribunal instance, tribunal commerce ou nul (plus récent des deux)

Le front devra dans tous les cas indiquer quelque part le type de greffe, et ainsi le front pourra déduire la bonne date à afficher.
Idem pour le PDF.
Ça évitera d'utiliser une même date pour les deux (pourquoi pas)

**Comment by brindu** [comment]
On est d'accord, il faut deux dates différentes pour les TC et les TITMC.

Je pense pas qu'il faille un modèle intelligent, on a juste besoin de la date des derniers fichiers synchronisés en base, peut importe qu'il s'agisse d'un stock ou d'une mise à jour quotidienne. Aujourd'hui je ne suis pas fan de la manière dont c'est récupéré, mais ça sera simplifié par #54

**Comment by brindu** [comment]
@Haelle Je peux clore cette issue du coup ?
